- name: testing variable precedence
  hosts: localhost
  vars:
    NAME: Satya
  # vars_files:
  # - variables.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: Enter your name
  #   private: false
  tasks:
  - name: var at task level
    ansible.builtin.debug:
      msg: "my name is : {{NAME}}"



      # 1st preference: from command line
      # 2nd - task level
      # 3rd - file