- name: ansible variable data types
  hosts: localhost
  vars:
  - AGE: 30 # number
  - NAME: "Satya" # string 
  - isFromIT: true # boolean
  - skills: #list
    - DevOps
    - Aws
    - Docker
  - Experience: map
      DevOps: 7
      Aws: 5
      Docker: 4
  tasks:
  - name: print number variable
    ansible.builtin.debug:
      msg: "Age is {{AGE}}"
  - name: print string variable
    ansible.builtin.debug:
      msg: "NAME is {{NAME}}"
  - name: print boolean variable
    ansible.builtin.debug:
      msg: "isFromIT is {{isFromIT}}"
  - name: print list variable
    ansible.builtin.debug:
      msg: "skills is {{skills}}"
  - name: print map variable
    ansible.builtin.debug:
      msg: "Experience is {{Experience}}"